version: 2.1 

orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

jobs: 
  build: 
    docker: 
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: bundle install --path vendor/bundle --jobs 20 --retry 5
      - run: |
          bundle exec rake test
      - store_test_results:
          path: /tmp/test-results
